1.0 ?
1fxe/Resource-Pack-Display pull request #8
Opened 2021-09-12 07:49 UTC by Wyvest

remake build.gradle
add essential (closes #7)
Make Ignore Overlay settings apply instantly
Add the option to retain overlays while randomly selecting a pack

2021-09-12 07:50 UTC, Wyvest commented
oh and ill do something to the rounded stuff

2021-09-12 07:56 UTC, Wyvest commented
ok nevermind i dont want to

2021-09-12 08:18 UTC, 1fxe requested changes
Rest seems fine

2021-09-12 08:18 UTC, 1fxe commented on src/main/java/dev/fxe/mods/resourcepackdisplay/data/Config.java
> +            type = PropertyType.SWITCH, name = "Display Pack Background",
Continuation Idents should be 4, but not really a big deal

2021-09-12 08:18 UTC, 1fxe commented on settings.gradle
> +                useModule("com.github.asbyth:ForgeGradle:${requested.version}")
Why? Normal forge works fine

2021-09-12 08:18 UTC, 1fxe commented on build.gradle
> +    exclude '*.jnilib'
These don't event get included in the jar anyway? (except META-INF)

2021-09-13 03:07 UTC, Wyvest commented on settings.gradle
> +                useModule("com.github.asbyth:ForgeGradle:${requested.version}")
> Why? Normal forge works fine

because normal forge doesn't work with gradle 6

2021-09-13 03:08 UTC, Wyvest commented on build.gradle
> +    exclude '*.jnilib'
> These don't event get included in the jar anyway? (except META-INF)

oh really? will remove then

2021-09-13 03:55 UTC, 1fxe commented on settings.gradle
> +                useModule("com.github.asbyth:ForgeGradle:${requested.version}")
gradle sssssadadasda

2021-09-13 03:56 UTC, merged